### ISSUE TITLE
Наполнение сайта

### ISSUE THREAD

**Issue by alamzh1** [BuladTS/link-aggregator#1]
Первая большая задача в спринте. Подзадачи

>поддержка комментариев к выпуску MarkDown.

**Comment by alamzh1** [comment]
Первая большая задача в спринте. Подзадача.
- [ ] Оформление главной страницы. #2
- [ ] Создание личного кабинета для пользователя. #3
- [ ] Сделать красивое анимирование сайта. #4
> Issue comments support MarkDown.
